spring:
  application:
    name: spring-boot-mongodb
  data:
    mongodb:
      uri: mongodb+srv://admin1234:admin1234@mern-cluster.4y1q3e6.mongodb.net/merndb?retryWrites=true&w=majority&appName=mern-cluster
      
server:
  port: 9080
